# Generated by Django 3.2.5 on 2021-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0002_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
